### ISSUE TITLE
Transcode

### ISSUE THREAD

**Issue by ghost** [jaymoulin/google-music-manager-uploader#1]
Hi.
First of all, I have to say that this tool works perfectly.
I just have one question.
Why when i normally run the daemon, and it is uploading a song, it echo the following?
`DEBUG:gmusicapi.Musicmanager1:running transcode command ['/usr/bin/ffmpeg', '-i', './songname.mp3', '-t', '60', '-ss', '100', '-b:a', '128k', '-f', 's16le', '-c', 'libmp3lame', 'pipe:1']`
I mean.. the file is already an mp3. Why should it transcode it? And.. when it says "128k", does it mean that it is actually compressing it?
Thanks in advance

**Comment by jaymoulin** [comment]
Google needs a sample to recognize a music to know if it's already uploaded or not. It's also required for the file to be MP3 encoded

**Comment by ghost** [comment]
Ok, thanks.
And what about the 128k?
I mean, it doesn't get uploaded with that compression level, right?

**Comment by jaymoulin** [comment]
You don't need to have an high quality for this. It represents a 15 secs sample

**Comment by ghost** [comment]
Oh, i see. It is used just for a check.
Is there a way to disable that or is it necessary?
Just because this process takes a while, and it seems a bit useless when uploading something new..

**Comment by jaymoulin** [comment]
> Google needs a sample to recognize a music to know if it's already uploaded or not. It's also required for the file to be MP3 encoded

The keyword here is **NEEDS**
