### ISSUE TITLE
Upload failing despite being authenticated already?

### ISSUE THREAD

**Issue by sprite-1** [jaymoulin/google-music-manager-uploader#2]
I entered the auth code that was given by Google and it seemed to accept everything, but when I try to upload a directory, it errors out on me with the following:

<details>
<pre>
sprite-1@G470:~/Music/神採りアルケミーマイスターサウンドコレクション$ google-music-auth 

Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?client_id=652850857958.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusicmanager&access_type=offline&response_type=code
Follow the prompts, then paste the auth code here and hit enter: [Redacted]
Logged successfully
sprite-1@G470:~/Music/神採りアルケミーマイスターサウンドコレクション$ google-music-upload -d Disc1 -o
INFO:google_music_manager_uploader.uploader_daemon:Init Daemon - Press Ctrl+C to quit
INFO:gmusicapi.Musicmanager1:!-- begin debug log --!
INFO:gmusicapi.Musicmanager1:version: 12.0.0
INFO:gmusicapi.Musicmanager1:logging to: /home/sprite-1/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Musicmanager1:initialized
INFO:gmusicapi.Musicmanager1:logged out
INFO:oauth2client.client:Refreshing access_token
INFO:gmusicapi.Musicmanager1:oauth successful
DEBUG:gmusicapi.Musicmanager1:AuthenticateUploader(args=['B8:70:F4:18:32:85', 'G470 (gmusicapi-12.0.0)'], kwargs={})
DEBUG:gmusicapi.Musicmanager1:response_type: AUTH_RESPONSE
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}
auth_status: NOT_SUBSCRIBED
auth_error: false
upauth_response {
  uploader_id: "B8:70:F4:18:32:85"
}

2019-02-05 08:47:14,708 - gmusicapi.Musicmanager1 (musicmanager:150) [ERROR]: upauth failure
Traceback (most recent call last):
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 251, in perform
    cls.check_success(response, parsed_response)
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/protocol/musicmanager.py", line 101, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 14: NOT_SUBSCRIBED. See http://goo.gl/O6xe7 for more information. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 144, in _perform_upauth
    uploader_name)
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/clients/shared.py", line 90, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 265, in perform
    raise_from(CallFailure(err_msg, e.callname), e)
  File "<string>", line 3, in raise_from
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 14: NOT_SUBSCRIBED. See http://goo.gl/O6xe7 for more information. 
(requests kwargs: {'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth', 'data': b'\n\x11B8:70:F4:18:32:85\x12\x17G470 (gmusicapi-12.0.0)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 à](\x000\x80}8\x00H\x01P\x01X\x0e`\x00j\x13\n\x11B8:70:F4:18:32:85')
ERROR:gmusicapi.Musicmanager1:upauth failure
Traceback (most recent call last):
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 251, in perform
    cls.check_success(response, parsed_response)
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/protocol/musicmanager.py", line 101, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 14: NOT_SUBSCRIBED. See http://goo.gl/O6xe7 for more information. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 144, in _perform_upauth
    uploader_name)
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/clients/shared.py", line 90, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/home/sprite-1/.local/lib/python3.6/site-packages/gmusicapi/protocol/shared.py", line 265, in perform
    raise_from(CallFailure(err_msg, e.callname), e)
  File "<string>", line 3, in raise_from
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 14: NOT_SUBSCRIBED. See http://goo.gl/O6xe7 for more information. 
(requests kwargs: {'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth', 'data': b'\n\x11B8:70:F4:18:32:85\x12\x17G470 (gmusicapi-12.0.0)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 à](\x000\x80}8\x00H\x01P\x01X\x0e`\x00j\x13\n\x11B8:70:F4:18:32:85')
Error with oauth credentials
</pre>
</details>
Am I missing something?

**Comment by jaymoulin** [comment]
You may want to try uploading a couple of songs via your browser to activate your account

**Comment by sprite-1** [comment]
There's no upload button on the web version for me even though I'm using Google chrome latest version

**Comment by jaymoulin** [comment]
Just drag and drop your mp3 in the interface

**Comment by sprite-1** [comment]
It just plays the audio file in the browser instead

https://streamable.com/9pcc7

**Comment by jaymoulin** [comment]
![peek 2019-02-05 11-25](https://user-images.githubusercontent.com/14236493/52267354-1bee7d80-2939-11e9-8b3d-664a5cf5d03a.gif)

Google says:
```
- Using Google Play Music for Chrome
    - Using a web browser, go to Google Play Music Settings.
    - Under "Music from this computer," select Unable to add songs.
```

**Comment by sprite-1** [comment]
These are the only options available on Google Play Music's settings though

![screenshot](https://user-images.githubusercontent.com/33685433/52267738-cdf76b00-2974-11e9-894a-3f387e728767.png)
![image](https://user-images.githubusercontent.com/33685433/52267759-dbacf080-2974-11e9-9b13-f270dcda7f99.png)
![image](https://user-images.githubusercontent.com/33685433/52267794-eb2c3980-2974-11e9-9ba3-e8071400dd09.png)
![image](https://user-images.githubusercontent.com/33685433/52267816-f717fb80-2974-11e9-8fb1-39e0df1b8ba3.png)

**Comment by jaymoulin** [comment]
Looks like this feature is not available for you (country / CC missing ...). You should look in Google Music support
