### ISSUE TITLE
Starting google-music-manager-uploader via systemd

### ISSUE THREAD

**Issue by lazarus-cm** [jaymoulin/google-music-manager-uploader#6]
Apologies if this isnt the best place to raise this, or if it is out of scope.

I have this setup on a raspberry pi and if I run it manually from the terminal its working great, however if I crate a systemd service file for this it fails to start:

`google-music-upload[29331]: ModuleNotFoundError: No module named 'google_music_manager_uploader'`

Is this just a misconfiguration by me or is it not compatible with systemd?

If its not supported what is the preferred means of auto-starting the daemon on linux?
* cron
* auto-start etc.

Thanks for your hard work!

**Comment by jaymoulin** [comment]
I think this is just a misconfiguration. You probably installed `google-music-manager-uploader` with user permissions and you try to run a module with a different user (maybe `sudo pip install google-music-manager-uploader --force-reinstall`).

I personally use the docker image (https://gitlab.com/jaymoulin/docker-google-music-uploader) that is run at start with my user specific crontab

**Comment by lazarus-cm** [comment]
That's entirely plausible. Since posting this earlier I've set it up to start via cron but thanks for responding so quickly.
