### ISSUE TITLE
google-music-upload does not update API

### ISSUE THREAD

**Issue by c0m3d1an** [jaymoulin/google-music-manager-uploader#8]
Hi-
I *believe* google-music-upload does not add files being uploaded to the google-music-deduplicate-api database.

I notice if I run google-music-upload-deduplicate, the API (and backend database) are updated, and if I run google-music-upload, the program "sees" the files that have been added via google-music-upload-deduplicate.

However, the scenario I would like is for files being uploaded to be ADDED to the google-music-upload-deduplicate-api database, so they will be SKIPPED on next upload.

If that IS the intended behavior, consider this a feature request.  If it is NOT, consider this a bug report.  :-)

**Comment by jaymoulin** [comment]
Thank you for reporting this. If you find this product useful, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))

I'm not really sure what you're refering to by "SKIPPING" on next upload for the process executed is to check on API before uploading if the MP3 file is already uploaded. If yes, then the file is not uploaded (you should see a log confirming this).

By the way, can you please provide some more informations for people to know how to reproduce such as version numbers you're using (API, Google Music Manager Upload)

**Comment by c0m3d1an** [comment]
Well, my understanding of what the steps should be:
1.  Run google-music-upload with the -d (API) option.
2.  google-music-upload checks to see if file exists in google-music-upload-api.
  a.  If track does not exist in GMUA , google-music-upload ADDS track to GMUA, then uploads it.
  b.  If track DOES exist in GMUA, google-music-upload does not attempt to upload current track and instead goes to the next one.

What is happening:
1.  Run google-music-upload with the -d (API) option.
2.  google-music-upload checks to see if file exists in google-music-upload-api.
  a.  If track does not exist in GMUA , google-music-upload ADDS track to GMUA, then uploads it.
  b.  If track DOES exist in GMUA, google-music-upload connects to Google and tries to upload it, and fails with TRACK EXISTS.

Versions:  
google-music-manager-auth     1.3.0         
google-music-manager-uploader 1.6.0
google-musicmanager-dedup-api - 1.0.0

**Comment by jaymoulin** [comment]
I think there is a confusion in your interpretations.

Here is what is coded:

- Run google-music-upload with the -d (API) option.
- google-music-upload checks to see if file path exists in google-music-upload-api.
  - If file path does not exist in GMDA
    - google-music-upload tries to upload
    - if upload succeeds, adds to GMDA, if not (already exists or not uploaded for any reason), does not add it.
  - if file path does exist in GMDA, skips file

Here are some proofs
https://github.com/jaymoulin/google-music-manager-uploader/blob/d8606371d054f69cdb9dca28ca6f60b8e5bc76a9/google_music_manager_uploader/uploader_daemon.py#L85
https://github.com/jaymoulin/google-music-manager-uploader/blob/d8606371d054f69cdb9dca28ca6f60b8e5bc76a9/google_music_manager_uploader/uploader_daemon.py#L90

And some logs that proves this behaviour with your actual versions:

```
googlemusic_1   | 2020-03-01 00:48:41,536 - google_music_manager_uploader.uploader_daemon - INFO - Init Daemon - Press Ctrl+C to quit
googlemusic_1   | 2020-03-01 00:51:48,782 - google_music_manager_uploader.uploader_daemon - INFO - Detected new files!
googlemusic_1   | 2020-03-01 00:51:48,785 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/01 - Seismic.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:51:48] "GET / HTTP/1.1" 404 -
googlemusic_1   | 2020-03-01 00:51:48,830 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? no
googlemusic_1   | 2020-03-01 00:51:49,071 - gmusicapi.Manager1 (manager:102) [WARNING]: problem gathering local info of ''/media/library/01 - Seismic.mp3''
googlemusic_1   | 2020-03-01 00:51:49,073 - google_music_manager_uploader.uploader_daemon - INFO - Not uploaded /media/library/01 - Seismic.mp3
mop-rpi_googlemusic_1 exited with code 0
googlemusic_1   | 2020-03-01 00:52:50,193 - google_music_manager_uploader.uploader_daemon - INFO - Init Daemon - Press Ctrl+C to quit
googlemusic_1   | 2020-03-01 00:52:51,648 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/01 - Seismic.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:52:51] "GET / HTTP/1.1" 404 -
googlemusic_1   | 2020-03-01 00:52:51,667 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? no
googlemusic_1   | 2020-03-01 00:53:27,984 - gmusicapi.Manager1 (manager:247) [WARNING]: upload of ''/media/library/01 - Seismic.mp3'' rejected: TrackSampleResponse code 4: ALREADY_EXISTS(3695b4fb-2145-35ea-89ed-490f8c643390)
googlemusic_1   | 2020-03-01 00:53:28,340 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: saving %s
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:53:29] "POST / HTTP/1.1" 204 -
mop-rpi_googlemusic_1 exited with code 0
googlemusic_1   | 2020-03-01 00:54:08,540 - google_music_manager_uploader.uploader_daemon - INFO - Init Daemon - Press Ctrl+C to quit
googlemusic_1   | 2020-03-01 00:54:45,230 - google_music_manager_uploader.uploader_daemon - INFO - Detected new files!
googlemusic_1   | 2020-03-01 00:54:45,231 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/01 - Seismic.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:54:45] "GET / HTTP/1.1" 204 -
googlemusic_1   | 2020-03-01 00:54:45,256 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? yes
googlemusic_1   | 2020-03-01 00:55:09,370 - google_music_manager_uploader.uploader_daemon - INFO - Detected new files!
googlemusic_1   | 2020-03-01 00:55:09,373 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/01 - Seismic.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:55:09] "GET / HTTP/1.1" 204 -
googlemusic_1   | 2020-03-01 00:55:09,402 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? yes
googlemusic_1   | 2020-03-01 00:55:09,403 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/02 - Blood Music.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:55:09] "GET / HTTP/1.1" 404 -
googlemusic_1   | 2020-03-01 00:55:09,432 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? no
googlemusic_1   | 2020-03-01 00:55:09,622 - gmusicapi.Manager1 (manager:102) [WARNING]: problem gathering local info of ''/media/library/02 - Blood Music.mp3''
googlemusic_1   | 2020-03-01 00:55:09,623 - google_music_manager_uploader.uploader_daemon - INFO - Not uploaded /media/library/02 - Blood Music.mp3
googlemusic_1   | 2020-03-01 00:55:51,916 - google_music_manager_uploader.uploader_daemon - INFO - Detected new files!
googlemusic_1   | 2020-03-01 00:55:51,919 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/01 - Seismic.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:55:51] "GET / HTTP/1.1" 204 -
googlemusic_1   | 2020-03-01 00:55:51,946 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? yes
googlemusic_1   | 2020-03-01 00:55:51,947 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/02 - Blood Music.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:55:51] "GET / HTTP/1.1" 404 -
googlemusic_1   | 2020-03-01 00:55:51,976 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? no
mop-rpi_googlemusic_1 exited with code 0
googlemusic_1   | 2020-03-01 00:56:51,665 - google_music_manager_uploader.uploader_daemon - INFO - Init Daemon - Press Ctrl+C to quit
googlemusic_1   | 2020-03-01 00:56:53,111 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/01 - Seismic.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:56:53] "GET / HTTP/1.1" 204 -
googlemusic_1   | 2020-03-01 00:56:53,141 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? yes
googlemusic_1   | 2020-03-01 00:56:53,142 - google_music_manager_uploader.uploader_daemon - INFO - Uploading /media/library/02 - Blood Music.mp3?
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:56:53] "GET / HTTP/1.1" 404 -
googlemusic_1   | 2020-03-01 00:56:53,171 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: file exists? no
googlemusic_1   | 2020-03-01 00:58:02,027 - google_music_manager_uploader.uploader_daemon - INFO - Deduplicate API: saving %s
googlededup_1   | 172.20.0.2 - - [29/Feb/2020 23:58:02] "POST / HTTP/1.1" 204 -
```

That being said, I agree that logs might not be clear enough but I don't see any bug here.
